Moved everything into a folder and added appeal command
Bot-detector/Bot-detector-Twitter pull request #10
Opened 2021-11-19 19:13 UTC by Ferrariic

2021-11-19 19:15 UTC, extreme4all commented
api seems a weird foldername for this project

2021-11-19 19:17 UTC, Ferrariic commented
> api seems a weird foldername for this project

That's fair, what should it be named?

2021-11-19 19:27 UTC, extreme4all requested changes

2021-11-19 19:27 UTC, extreme4all commented on twitter_bot/Commands/appeal.py
> +        except Exception as e:
try not to catch generic exceptions

2021-11-19 19:27 UTC, extreme4all commented on twitter_bot/Commands/appeal.py
> +            print(f'Status update error. {e}')
make use of logging repository instead of printing

2021-11-19 19:46 UTC, extreme4all commented
remove example-command.py

instead of having big if else blocks, make a negating if function

if not true:
    return something
    
avoid generic Exceptions
make use of logging library

type hinting

for bans just hit the api

seems like all the functions have something generic going on

can text_removed_at be renamed to text
rename api to twitter_api?
shouldn't twitter_api be a global variable

do we have to cycle through like a dict of our commands, how does discord handle this?
func = [v for dict_functions if k == command][0]
msg = func()

your functions should return the message to be sent
def func(text, parent_tweet_id):
    api.update_status(
        status="a message",
        in_reply_to_status_id=parent_tweet_id, auto_populate_reply_metadata=True
    )

2021-11-20 07:48 UTC, Ferrariic commented
All major instances should be resolved, will do exception catching in next branch

2021-11-20 07:50 UTC, Ferrariic commented
Resolves #9 #3 #2

2021-11-20 14:25 UTC, extreme4all commented
> Resolves #9 #3 #2

tagging is good, but i also linked the issue

2021-11-20 14:25 UTC, Ferrariic commented
> > Resolves #9 #3 #2
> 
> tagging is good, but i also linked the issue

Thanks!

2021-11-20 20:11 UTC, merged